function plot_cb_img_info_2D(cb_img,points_p,four_points_p,A,distortion,rotation,translation,homography_refine,calib_config,a)
    % This will plot calibration info over a calibration board image
        
    if ~exist('a','var')
        f = figure(); 
        a = axes(f);
    end
    cla(a);
    
    % Show image
    imshow(cb_img.get_gs(),[],'parent',a);
    hold(a,'on');
    
    % Plot border around checkers
    height_offset = (calib_config.four_point_height-calib_config.num_squares_height*calib_config.square_size)/2;
    width_offset = (calib_config.four_point_width-calib_config.num_squares_width*calib_config.square_size)/2;
    for i = 1:calib_config.num_squares_width
        for j = 1:calib_config.num_squares_height            
            % Get checker coords
            boarder_x_w = [(i-1)*calib_config.square_size  ...
                           (i-1)*calib_config.square_size ...
                           i*calib_config.square_size ...
                           i*calib_config.square_size ...
                           (i-1)*calib_config.square_size]'+width_offset;
            boarder_x_w = [linspace(boarder_x_w(1),boarder_x_w(2),20) ...
                           linspace(boarder_x_w(2),boarder_x_w(3),20) ...
                           linspace(boarder_x_w(3),boarder_x_w(4),20) ...
                           linspace(boarder_x_w(4),boarder_x_w(1),20)]'; 
            boarder_y_w = [(j-1)*calib_config.square_size ...
                           j*calib_config.square_size ...
                           j*calib_config.square_size ...
                           (j-1)*calib_config.square_size ...
                           (j-1)*calib_config.square_size]'+height_offset;
            boarder_y_w = [linspace(boarder_y_w(1),boarder_y_w(2),20) ...
                           linspace(boarder_y_w(2),boarder_y_w(3),20) ...
                           linspace(boarder_y_w(3),boarder_y_w(4),20) ...
                           linspace(boarder_y_w(4),boarder_y_w(1),20)]'; 

            % Plot
            boarder_p_p = alg.p_m(A, ...
                                  distortion, ...
                                  rotation, ...
                                  translation, ...
                                  [boarder_x_w boarder_y_w]); 
            plot(boarder_p_p(:,1),boarder_p_p(:,2),'w-','LineWidth',3,'parent',a);
            plot(boarder_p_p(:,1),boarder_p_p(:,2),'k-','LineWidth',1,'parent',a);
        end
    end        
    
    % Plot axes
    axes_coords_w = [0 0;
                     calib_config.square_size 0;
                     0 0;
                     0 calib_config.square_size];
    axes_coords_p = alg.p_m(A, ...
                            distortion, ...
                            rotation, ...
                            translation, ...
                            axes_coords_w);  
    quiver(axes_coords_p(1:2:end,1), ...
           axes_coords_p(1:2:end,2), ...
           axes_coords_p(2:2:end,1)-axes_coords_p(1:2:end,1), ...
           axes_coords_p(2:2:end,2)-axes_coords_p(1:2:end,2), ...
           'color','r','LineWidth',2,'AutoScale','off','parent',a);
             
    text_coords_w = [1.5*calib_config.square_size 0;
                     0 1.5*calib_config.square_size];                 
    text_coords_p = alg.p_m(A, ...
                            distortion, ...
                            rotation, ...
                            translation, ...
                            text_coords_w);  
    text(text_coords_p(1,1),text_coords_p(1,2),'x', ...
         'FontSize',12,'HorizontalAlignment','center','color','r', ...
         'FontWeight','bold','parent',a);
    text(text_coords_p(2,1),text_coords_p(2,2),'y', ...
         'FontSize',12,'HorizontalAlignment','center','color','r', ...
         'FontWeight','bold','parent',a);
     
    % Plot refinement windows around points   
    for i = 1:size(points_p,1)          
        % Get window points in pixel coordinates
        [~,~,win_point_corners] = alg.refine_window_p(points_p(i,:), ...
                                                      homography_refine, ...
                                                      cb_img.get_width(), ...
                                                      cb_img.get_height(), ...
                                                      calib_config);
                                                  
                                                  
        
        % Plot        
        patch(a,win_point_corners([1 2 4 3],1),win_point_corners([1 2 4 3],2), ...
              'k','FaceAlpha',0.25,'EdgeColor','w','EdgeAlpha',0.25);
    end     
        
    % Plot displacements    
    points_m = alg.p_m(A, ...
                       distortion, ...
                       rotation, ...
                       translation, ...
                       alg.cb_points(calib_config));    
    quiver(points_p(:,1), ...
           points_p(:,2), ...
           points_m(:,1)-points_p(:,1), ...
           points_m(:,2)-points_p(:,2), ...
           'color','b','LineWidth',1,'AutoScale','off','parent',a);
    
    % Plot points
    plot(points_m(:,1),points_m(:,2),'r+','MarkerSize',6,'LineWidth',1,'parent',a);
    plot(points_p(:,1),points_p(:,2),'gs','MarkerSize',6,'LineWidth',1,'parent',a);
    
    % Plot four points
    plot(four_points_p(:,1),four_points_p(:,2),'bo','MarkerSize',12,'LineWidth',2,'parent',a); 
       
    % Plot principle point
    plot([A(1,3) A(1,3)],[1 cb_img.get_height()],'--g','parent',a);
    plot([1 cb_img.get_width()],[A(2,3) A(2,3)],'--g','parent',a);
       
    % Plot center of image (to compare principle point)
    plot([(cb_img.get_width()+1)/2 (cb_img.get_width()+1)/2],[1 cb_img.get_height()],'--r','parent',a);
    plot([1 cb_img.get_width()],[(cb_img.get_height()+1)/2 (cb_img.get_height()+1)/2],'--r','parent',a);
    
    % Remove hold
    drawnow
    hold(a,'off');
end
