function plot_single_fp_detect_LoG(array, p_fps, blobs, ellipses, a)
    % This plots debugging info for four point LoG detection

    if ~exist('a', 'var')
        f = figure();
        a = axes(f);
    end

    % Show image
    imshow(array, [], 'Parent', a)
    hold(a, 'on');

    % Plot four points
    plot(p_fps(1:2, 1), p_fps(1:2, 2), '-o', 'Color', [0.0000 0.0000 1.0000], ...
         'MarkerSize', 8, 'LineWidth', 2, 'parent', a);
    plot(p_fps(2:3, 1), p_fps(2:3, 2), '-o', 'Color', [1.0000 0.1034 0.7241], ...
         'MarkerSize', 8, 'LineWidth', 2, 'parent', a);
    plot(p_fps(3:4, 1), p_fps(3:4, 2), '-o', 'Color', [1.0000 0.8276 0.0000], ...
         'MarkerSize', 8, 'LineWidth', 2, 'parent', a);

    % Plot blobs and ellipses
    axes(a);
    for i = 1:size(blobs, 1)
        external.ellipse(blobs(i, 3), ...
                         blobs(i, 4), ...
                         blobs(i, 5), ...
                         blobs(i, 1), ...
                         blobs(i, 2), ...
                         'r');
    end
    for i = 1:size(ellipses, 1)
        external.ellipse(ellipses(i, 3), ...
                         ellipses(i, 4), ...
                         ellipses(i, 5), ...
                         ellipses(i, 1), ...
                         ellipses(i, 2), ...
                         'g');
    end

    % Remove hold
    hold(a, 'off');
end
