function write_stereo_calib(cb_imgs,board_points_ps,four_points_ps,A,distortion,rotations,translations,homographies_refine,cal_config,file_path)
    % Writes outputs of stereo calibration to a file, so it can be read
    % again later.
    % 
    % Inputs:
    
    % Write left
    util.write_single_calib(cb_imgs.L, ...
                            board_points_ps.L, ...
                            four_points_ps.L, ...
                            A.L, ...
                            distortion.L, ...
                            rotations.L, ...
                            translations.L, ...
                            homographies_refine.L, ...
                            cal_config, ...
                            file_path, ...
                            '_L');
                        
    % Write right
    util.write_single_calib(cb_imgs.R, ...
                            board_points_ps.R, ...
                            four_points_ps.R, ...
                            A.R, ...
                            distortion.R, ...
                            rotations.R, ...
                            translations.R, ...
                            homographies_refine.R, ...
                            cal_config, ...
                            file_path, ...
                            '_R', ...
                            true);
end