function test_write_single_cam()
    % Get temporary file
    temp_path = tempname;

    cam.intrin.A = eye(3);
    cam.intrin.d = ones(3, 1);

    cam.extrin.img_cb = class.img.path('test');
    cam.extrin.R = eye(3);
    cam.extrin.t = ones(3, 1);
    cam.extrin.p_cb_p_ds = ones(1, 2);
    cam.extrin.cov_cb_p_ds = {eye(2, 2)};
    cam.extrin.p_cb_p_d_ms = ones(1, 2);
    cam.extrin.idx_valid = ones(1, 1);
    cam.extrin.p_fp_p_ds = ones(4, 2);
    cam.R_1 = eye(3);
    cam.t_1 = zeros(3, 1);

    util.write_single_cam(cam, temp_path);

    % Check file contents
    assert(strcmp(fileread(temp_path), ['% Intrinsics' newline, ...
                                        'A = ' newline, ...
                                        '1 0 0' newline, ...
                                        '0 1 0' newline, ...
                                        '0 0 1' newline newline, ...
                                        'd = ' newline, ...
                                        '1' newline, ...
                                        '1' newline, ...
                                        '1' newline newline, ...
                                        '% Extrinsics1' newline, ...
                                        'obj_img1 = class.img.path' newline, ...
                                        'state_img1 = test' newline newline, ...
                                        'R1 = ' newline, ...
                                        '1 0 0' newline, ...
                                        '0 1 0' newline, ...
                                        '0 0 1' newline newline, ...
                                        't1 = ' newline, ...
                                        '1' newline, ...
                                        '1' newline, ...
                                        '1' newline newline, ...
                                        'p_cb_p_ds1 = ' newline, ...
                                        '1 1' newline newline, ...
                                        'cov_cb_p_ds1 = ' newline, ...
                                        '1 0' newline, ...
                                        '0 1' newline newline, ...
                                        'p_cb_p_d_ms1 = ' newline, ...
                                        '1 1' newline newline, ...
                                        'idx_valid1 = ' newline, ...
                                        '1' newline newline, ...
                                        'p_fp_p_ds1 = ' newline, ...
                                        '1 1' newline, ...
                                        '1 1' newline, ...
                                        '1 1' newline, ...
                                        '1 1' newline newline, ...
                                        'R_1 = ' newline, ...
                                        '1 0 0' newline, ...
                                        '0 1 0' newline, ...
                                        '0 0 1' newline newline, ...
                                        't_1 = ' newline, ...
                                        '0' newline, ...
                                        '0' newline, ...
                                        '0' newline newline]));

    % Remove temporary file
    delete(temp_path);
end
